### PR TITLE
hip-applicationSigns-draft - add initial files

### PR DESCRIPTION
**Pull request by justin-atwell**
**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by gregscullard — CHANGES_REQUESTED** [review]
line 65, maybe add a comment to indicate the client's operator and key don't need to be set since the transaction is fully signed, the client only acts as "transport" here.

**Review by gregscullard — CHANGES_REQUESTED** [review]
Line 60, maybe add comment to indicate the transaction should be "shipped" to the other user for signing using a REST api or other protocol.

**Comment by gregscullard** [comment]
We probably should include how a transaction can be signed using a signer which exemplifies how an external "process" can sign a transaction on behalf of the application.

**Review by sergmetelin — APPROVED** [review]
LGTM

**Review by gregscullard — APPROVED** [review]
LGTM

**Pull request merged**
