### PR TITLE
Update hip-765.md

### PR DESCRIPTION
**Pull request by SimiHunjan**
- This HIP did not call out that the `adminKey` can also sign the `TokenUpdateTransaction` to modify the `metadata` field on a NFT collection.

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by SimiHunjan** [comment]
cc: @netopyr @Neeharika-Sompalli @ty-swirldslabs

**Review by Neeharika-Sompalli — APPROVED** [review]
LGTM! Thanks @SimiHunjan

**Comment by SimiHunjan** [comment]
@mgarbs not sure who needs to be assigned to review this from a required reviewer

**Comment by mgarbs** [comment]
> @mgarbs not sure who needs to be assigned to review this from a required reviewer

Hi Simi! Could you resolve these two validation errors? https://github.com/hashgraph/hedera-improvement-proposal/actions/runs/8802584923/job/24158660356?pr=949#:~:text=21-,Error%3A%20updated%20date%20doesnt%20match%20current%20date%20in%20header%2C%20add%20current,at%20processTicksAndRejections%20(internal/process/task_queues.js%3A97%3A5),-28

Other than that looks great!

**Review by mgarbs — APPROVED** [review]

**Pull request merged**
