### PR TITLE
hip-17.md

### PR DESCRIPTION
**Pull request by corviato1**

### CODE REVIEW

**Comment by kenthejr** [comment]
Any chance you can find someone in the community to help you define the specification for this HIP? As of yet it is incomplete. It is a great jumping off point for discussion, but it needs some more specification work before it can be merged.

**Comment by mattsmithies** [comment]
An approach to solving NFT royalties is with Atomic Swaps with multiple recipients whilst having an audit trail on HCS.

You can do that now up to a maximum of 5 recipients based on current network constraints. So in other terms, there would be the ability to create different topics relating to different entities relating to their own configured royalty rate.

An example of such a transfer (without HCS audit trail) is [on my unibar repo](https://github.com/trustenterprises/unibar-prototype/blob/master/app/hashgraph/tokens/index.ts#L206).

The transfer and HCS audit trail would act as separate calls within the same function and would be easiest to implement using a custodian payment model, so an NFT issuer/service pays for the gas which means that this action can be wrapped up as an API. 

Finally, to link the transfers to a HCS you'd add the information of a related token and expected royalty within the genesis message, thus providing a link. As everything is onchain and publically view it would be trivial to discover if particular royalties weren't recorded and paid.

**Comment by kenthejr** [comment]
Please review https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-1.md for a list of Types and Categories.

**Comment by mattsmithies** [comment]
@kenthejr is this now superseded by [HIP-18](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-18.md)?

**Comment by sergmetelin** [comment]
@mattsmithies yep.
Superseded by [HIP-18](https://github.com/hashgraph/hedera-improvement-proposal/blob/master/HIP/hip-18.md). Closing this one down.

**Pull request closed without merging**
