### PR TITLE
feat: Improve record stream legibility and extensibility 

### PR DESCRIPTION
**Pull request by tinker-michaelj**
**Description**:
 - Adds HIP with 5 small proposals that each improve the legibility and extensibility of the record stream.

### CODE REVIEW

**Review by netopyr — DISMISSED** [review]
LGTM - thanks @tinker-michaelj, these are very useful improvements

**Review by mgarbs — APPROVED** [review]

**Comment by Neurone** [comment]
Hi @tinker-michaelj , overall the HIP-993 looks good to me.

I have some of doubts about features #2 (Unified child consensus times) and https://github.com/hashgraph/hedera-improvement-proposal/pull/6 (Use natural order for preceding dispatch records).

In general, do those updates change the values on the record files?

In particular, does #2 imply changes in the consensusTimestamp or parentConsensusTimestamp fields and their values I can read in the record file? I don't see any `creation_time` at that level, so I'm unsure if #2 is a service or mirror node feature.

Also, does https://github.com/hashgraph/hedera-improvement-proposal/pull/6 imply changes in field values (the nonce), or is it just a reordering in how we write information in record files without real impact on fields and values?

Can you clarify in the HIP the systems/components (consensus nodes, mirror nodes, explorers, etc.) impacted by each of the six proposed changes?

**Comment by tinker-michaelj** [comment]
> Hi @tinker-michaelj , overall the HIP-993 looks good to me.
> 
> I have some of doubts about features nr.2 (Unified child consensus times) and nr.6 (Use natural order for preceding dispatch records).
> 
> In general, do those updates change the values on the record files?
> 
> In particular, does #2 imply changes in the `consensusTimestamp` or `parentConsensusTimestamp` fields and their values I can read in the record file? I don't see any `creation_time` at that level, so I'm unsure if nr.2 is a service or mirror node feature.
> 
> Also, does nr.6 imply changes in field values (the nonce), or is it just a reordering in how we write information in record files without real impact on fields and values?
> 
> Can you clarify in the HIP the systems/components (consensus nodes, mirror nodes, explorers, etc.) impacted by each of the six proposed changes?

Hi @Neurone , thanks for the questions!

Item **"Use natural order for preceding dispatch records"** is a re-ordering of information with no semantic impact. (The `nonce` in a `TransactionID` is just a [unique value](https://github.com/hashgraph/hedera-protobufs/blob/54b258dfa27866d2654bb036112298b5a6693505/services/basic_types.proto#L228) with no other meaning.) All other values 

Item **"Unified child consensus times"** does not change any value externalized in the block stream. It only changes the nanosecond offset of the immutable [`mint_time`](https://github.com/hashgraph/hedera-protobufs/blob/54b258dfa27866d2654bb036112298b5a6693505/services/state/token/nft.proto#L59) (or sometimes ,"`creation_time`") that is stored with the NFT in consensus node state. Mirror node teams are free to ignore this or not.  

The impact of this HIP is almost 100% on consensus node as it helps lays the groundwork to create block streams.

**Comment by Neurone** [comment]
Hi @tinker-michaelj , thanks for the clarifications.

I understand that the official mirror node's importer does not use `mint_time` at all, but it uses the `consensusTimestamp` of the tx or child tx. I'm unaware of any mirror node custom implementation used in production, so I don't see any impact.

So, to verify I understood correctly about the unified child consensus time:

1. After this HIP, if the mint operation happens in a child transaction, the `mint_time` value will be **earlier** than the child tx consensus timestamp because it takes the parent consensus timestamp value.
2. This HIP does not impact the values of `consensusTimestamp`, `parentConsensusTimestamp`, `nonce`, or any other values in the record file.
3. We are not changing or planning to change the synthetic consensus time functionality. From an external reader's point of view (record stream reader/mirror node's importer) there will be still a consensus timestamp and a +1 nanosecond for each child tx.

And about the natural ordering:

1. The new ordering in the record file is only estetic, so that for example in a tx like [this](https://mainnet-public.mirrornode.hedera.com/api/v1/transactions/0.0.3929606-1718150300-262000000), now I see transaction 1 first, and than transaction 0 just after it. After the new HIP I will read transaction 0, and after that transaction 1.

```txt
=== Transaction #1 HoWN5UvBADKL7DEOmlYRNCzWbgoTGW5B9CG4aHWL1OTVlqo3uSLK5g4G4/8wo0Is 1e858de54bc100328bec310e9a5611342cd66e0a13196e41f421b868758bd4e4d596aa37b922cae60e06e3ff30a3422c ===
{
  transaction: {
    signedTransactionBytes: 'CoABChYKCwicyaOzBhCAm/d8EgUYhuzvASABWmYKIhIguFreaTxwj/LB5bLXZH4wFS9u4fdpJNq86DoxCkYqrYdKBQiAztoDahRhdXRvLWNyZWF0ZWQgYWNjb3VudJIBIhIguFreaTxwj/LB5bLXZH4wFS9u4fdpJNq86DoxCkYqrYc='
  },
  record: {
    receipt: { status: 'SUCCESS', accountID: { accountNum: '6134246' } },
    transactionHash: 'HoWN5UvBADKL7DEOmlYRNCzWbgoTGW5B9CG4aHWL1OTVlqo3uSLK5g4G4/8wo0Is',
    consensusTimestamp: { seconds: '1718150303', nanos: 526849002 },
    transactionID: {
      transactionValidStart: { seconds: '1718150300', nanos: 262000000 },
      accountID: { accountNum: '3929606' },
      nonce: 1
    },
    memo: 'auto-created account',
    transactionFee: '54047391',
    transferList: {}
  }
}

=== Body #1 HoWN5UvBADKL7DEOmlYRNCzWbgoTGW5B9CG4aHWL1OTVlqo3uSLK5g4G4/8wo0Is 1e858de54bc100328bec310e9a5611342cd66e0a13196e41f421b868758bd4e4d596aa37b922cae60e06e3ff30a3422c ===
{
  transactionID: {
    transactionValidStart: { seconds: '1718150300', nanos: 262000000 },
    accountID: { accountNum: '3929606' },
    nonce: 1
  },
  cryptoCreateAccount: {
    key: { ed25519: 'uFreaTxwj/LB5bLXZH4wFS9u4fdpJNq86DoxCkYqrYc=' },
    autoRenewPeriod: { seconds: '7776000' },
    memo: 'auto-created account',
    alias: 'EiC4Wt5pPHCP8sHlstdkfjAVL27h92kk2rzoOjEKRiqthw=='
  }
}

=== Transaction #0 ockpcdkb6GCRXULA8Ri2ICihOF2Xw05X0yNjD629uR+vrIb8M4scf5JQZSkJUBFe a1c92971d91be860915d42c0f118b62028a1385d97c34e57d323630fadbdb91fafac86fc338b1c7f925065290950115e ===
{
  transaction: {
    signedTransactionBytes: 'CmAKFAoLCJzJo7MGEICb93wSBRiG7O8BEgIYCBjJ0w8iAwi0AXI7CjkKKgokIiISILha3mk8cI/yweWy12R+MBUvbuH3aSTavOg6MQpGKq2HEICJegoLCgUYhuzvARD/iHoSZgpkCiCwUgWSfTjea9DJ0F97OknnLsjNtvCIh87QK2yMEz3GeB
pAaVQPguyb4AEIpHr1rbj/CBxbQ2CbPStvLAtTi6d51p1kjGcKekKy98cMWAOENdEHBW9qm3VrACXwV5OVruydAg=='
  },
  record: {
    receipt: {
      status: 'SUCCESS',
      exchangeRate: {
        currentRate: {
          hbarEquiv: 30000,
          centEquiv: 262562,
          expirationTime: { seconds: '1718150400' }
        },
        nextRate: {
          hbarEquiv: 30000,
          centEquiv: 262920,
          expirationTime: { seconds: '1718154000' }
        }
      }
    },
    transactionHash: 'ockpcdkb6GCRXULA8Ri2ICihOF2Xw05X0yNjD629uR+vrIb8M4scf5JQZSkJUBFe',
    consensusTimestamp: { seconds: '1718150303', nanos: 526849003 },
    transactionID: {
      transactionValidStart: { seconds: '1718150300', nanos: 262000000 },
      accountID: { accountNum: '3929606' }
    },
    transactionFee: '54162549',
    transferList: {
      accountAmounts: [
        { accountID: { accountNum: '8' }, amount: '4664' },
        { accountID: { accountNum: '98' }, amount: '48742097' },
        { accountID: { accountNum: '800' }, amount: '5415788' },
        { accountID: { accountNum: '3929606' }, amount: '-55162549' },
        { accountID: { accountNum: '6134246' }, amount: '1000000' }
      ]
    }
  }
}

=== Body #0 ockpcdkb6GCRXULA8Ri2ICihOF2Xw05X0yNjD629uR+vrIb8M4scf5JQZSkJUBFe a1c92971d91be860915d42c0f118b62028a1385d97c34e57d323630fadbdb91fafac86fc338b1c7f925065290950115e ===
{
  transactionID: {
    transactionValidStart: { seconds: '1718150300', nanos: 262000000 },
    accountID: { accountNum: '3929606' }
  },
  nodeAccountID: { accountNum: '8' },
  transactionFee: '256457',
  transactionValidDuration: { seconds: '180' },
  cryptoTransfer: {
    transfers: {
      accountAmounts: [
        {
          accountID: { alias: 'EiC4Wt5pPHCP8sHlstdkfjAVL27h92kk2rzoOjEKRiqthw==' },
          amount: '1000000'
        },
        { accountID: { accountNum: '3929606' }, amount: '-1000000' }
      ]
    }
  }
}
```

Side question on the `nonce`: do you mean that is wrong/optimistic consider use it to determine the order of the children's transactions with respect to the father, which is always 0?

**Comment by tinker-michaelj** [comment]
Hi @Neurone , 

All three points on unified child consensus time are exactly correct.

The example auto-account creation you linked is not one of the cases addressed by this HIP; that ordering would be unchanged. The ordering only changes if the `CryptoTransfer` is **itself** a synthetic child of a parent `ContractCall`. Before this HIP, the auto-creation triggered by the `CryptoTransfer` would "jump" all the way back before the parent `ContractCall`. After this HIP, the auto-creation appears after the parent and directly before the `CryptoTransfer` that triggered it.

 >Side question on the nonce: do you mean that is wrong/optimistic consider use it to determine the order of the children's transactions with respect to the father, which is always 0?

Yes, the `nonce` should not be interpreted as having any meaning other than distinguishing the `TransactionID` from other ids with the same `accountID` and `transactionValidStart`.

**Comment by Neurone** [comment]
Thank you very much! Now everything is clear to me about this HIP.

**Comment by tinker-michaelj** [comment]
> Thank you very much! Now everything is clear to me about this HIP.

Np, tyvm!

**Pull request merged**
