### PR TITLE
HIP 17 - HTS NFT support 

### PR DESCRIPTION
**Pull request by Daniel-K-Ivanov**
**Details**
- Proposal for extending the HTS service with support for NFTs
- Consolidates IWA specification and HTS API
- The proposed API aligns with the pending NFT design and specification referring to `MerkleInvertibleMap`

### CODE REVIEW

**Comment by corviato1** [comment]
There is a hip-17 in the pipeline that predates this one.

**Review by donaldthibeau — APPROVED** [review]

**Comment by Daniel-K-Ivanov** [comment]
> There is a hip-17 in the pipeline that predates this one.

I wasn't sure whether we are counting only the merged ones or the pending ones as well. So should it be 17 or 18?

**Comment by kenthejr** [comment]
> There is a hip-17 in the pipeline that predates this one.

HIP numbers are assigned by editors when merged. This one will most likely become HIP 17. I added a comment to your proposal.

**Review by kenthejr — COMMENTED** [review]
This looks great. Can we get the meta-data updated? The `type` property should be "Standards Track" & `category` should be "Service".

Other than that, it looks ready to merge.

**Review by kenthejr — APPROVED** [review]
Thank you. It looks good.

**Pull request merged**
